In [3]:
#Ques 1
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


In [12]:
#Ques 2
print("Elements present in list {}".format('list_'))
for i in list_:
    print(type(i),end=" ")
print()
print("Element present in numpy array {}".format('array_list'))
for i in array_list:
    print(type(i),end=' ')

Elements present in list list_
<class 'str'> <class 'str'> <class 'str'> <class 'str'> <class 'str'> 
Element present in numpy array array_list
<class 'numpy.str_'> <class 'numpy.str_'> <class 'numpy.str_'> <class 'numpy.str_'> <class 'numpy.str_'> 

In [13]:
#Ques 3
#Elements present in list_ is of 'str' type whereas in array_list is of 'int' type
array_list = np.array(object = list_, dtype = int)
print("Elements present in list {}".format('list_'))
for i in list_:
    print(type(i),end=" ")
print()
print("Element present in numpy array {}".format('array_list'))
for i in array_list:
    print(type(i),end=' ')

Elements present in list list_
<class 'str'> <class 'str'> <class 'str'> <class 'str'> <class 'str'> 
Element present in numpy array array_list
<class 'numpy.int32'> <class 'numpy.int32'> <class 'numpy.int32'> <class 'numpy.int32'> <class 'numpy.int32'> 

In [15]:
#Ques 4
import numpy as np
num_list=[[1,2,3],[4,5,6]]
num_array=np.array(object=num_list)
#Shape is used to return a tuple in form of (rows,cols)
print(num_array.shape)
#Size is used to return the no of elements present in num_array
print(num_array.size)

(2, 3)
6


In [17]:
#Ques 5
import numpy as np
arr=np.zeros((3,3))
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
2
(3, 3)
9


In [19]:
#Ques 6
#Identity matrix of shape (5,5)
import numpy as np
arr=np.identity(5,dtype='int')
print(arr)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
